### ISSUE TITLE
Can not get FileTea to build with Evd0.2

### ISSUE THREAD

**Issue by Toys0125** [elima/FileTea#12]
```
make  all-recursive
make[1]: Entering directory '/home/dev/Desktop/FileTea/FileTea'
Making all in filetea
make[2]: Entering directory '/home/dev/Desktop/FileTea/FileTea/filetea'
  CCLD     filetea
/usr/bin/ld: filetea-filetea-main.o: in function `main':
/home/dev/Desktop/FileTea/FileTea/filetea/filetea-main.c:673: undefined reference to `evd_ipc_mechanism_use_transport'
/usr/bin/ld: filetea-filetea-protocol.o: in function `filetea_protocol_init':
/home/dev/Desktop/FileTea/FileTea/filetea/filetea-protocol.c:92: undefined reference to `evd_jsonrpc_set_callbacks'
/usr/bin/ld: filetea-filetea-transfer.o: in function `filetea_transfer_start':
/home/dev/Desktop/FileTea/FileTea/filetea/filetea-transfer.c:575: undefined reference to `evd_web_service_respond_headers'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:513: filetea] Error 1
make[2]: Leaving directory '/home/dev/Desktop/FileTea/FileTea/filetea'
make[1]: *** [Makefile:519: all-recursive] Error 1
make[1]: Leaving directory '/home/dev/Desktop/FileTea/FileTea'
make: *** [Makefile:389: all] Error 2
```

**Comment by elima** [comment]
This should have been fixed already some time ago.
